# ── CloudFront ────────────────────────────────────────────────────────────────
#
# Two distributions:
#   web   → novakidlife.com / www.novakidlife.com → S3 web bucket
#   media → media.novakidlife.com                 → S3 media bucket

# ── Origin Access Controls (OAC) ─────────────────────────────────────────────

resource "aws_cloudfront_origin_access_control" "web" {
  name                              = "${var.project}-web-oac"
  description                       = "OAC for novakidlife web S3 bucket"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

resource "aws_cloudfront_origin_access_control" "media" {
  name                              = "${var.project}-media-oac"
  description                       = "OAC for novakidlife media S3 bucket"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

# ── Cache policies ────────────────────────────────────────────────────────────

# Managed cache policy: CachingOptimized (AWS-managed, ID well-known)
locals {
  cf_cache_optimized_id          = "658327ea-f89d-4fab-a63d-7e88639e58f6"
  cf_cache_optimized_compression = "b2884449-e4de-46a7-ac36-70bc7f1ddd6d"
}

# Long-lived cache for media assets (1 year, immutable WebP files)
resource "aws_cloudfront_cache_policy" "media_immutable" {
  name        = "${var.project}-media-immutable"
  comment     = "1-year cache for immutable WebP image assets"
  default_ttl = 31536000
  max_ttl     = 31536000
  min_ttl     = 0

  parameters_in_cache_key_and_forwarded_to_origin {
    cookies_config {
      cookie_behavior = "none"
    }
    headers_config {
      header_behavior = "none"
    }
    query_strings_config {
      query_string_behavior = "none"
    }
    enable_accept_encoding_gzip   = true
    enable_accept_encoding_brotli = true
  }
}

# Short cache for HTML pages (1 hour — regenerated by CI/CD on deploy)
resource "aws_cloudfront_cache_policy" "web_html" {
  name        = "${var.project}-web-html"
  comment     = "1-hour cache for static HTML pages"
  default_ttl = 3600
  max_ttl     = 86400
  min_ttl     = 0

  parameters_in_cache_key_and_forwarded_to_origin {
    cookies_config {
      cookie_behavior = "none"
    }
    headers_config {
      header_behavior = "none"
    }
    query_strings_config {
      query_string_behavior = "none"
    }
    enable_accept_encoding_gzip   = true
    enable_accept_encoding_brotli = true
  }
}

# ── Web distribution (novakidlife.com) ────────────────────────────────────────

resource "aws_cloudfront_distribution" "web" {
  enabled             = true
  is_ipv6_enabled     = true
  http_version        = "http2and3"
  default_root_object = "index.html"
  comment             = "NovaKidLife web — ${var.environment}"

  aliases = var.web_acm_certificate_arn != "" ? [
    var.domain_name,
    var.www_domain_name
  ] : []

  origin {
    domain_name              = aws_s3_bucket.web.bucket_regional_domain_name
    origin_id                = "S3-${aws_s3_bucket.web.id}"
    origin_access_control_id = aws_cloudfront_origin_access_control.web.id
  }

  # Default: serve HTML with 1-hour cache
  default_cache_behavior {
    target_origin_id       = "S3-${aws_s3_bucket.web.id}"
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD", "OPTIONS"]
    cached_methods         = ["GET", "HEAD"]
    compress               = true
    cache_policy_id        = aws_cloudfront_cache_policy.web_html.id

    function_association {
      event_type   = "viewer-request"
      function_arn = aws_cloudfront_function.url_rewrite.arn
    }
  }

  # Static assets (_next/static/*) — long-lived cache
  ordered_cache_behavior {
    path_pattern           = "_next/static/*"
    target_origin_id       = "S3-${aws_s3_bucket.web.id}"
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    compress               = true
    cache_policy_id        = aws_cloudfront_cache_policy.media_immutable.id
  }

  # Fonts — long-lived cache
  ordered_cache_behavior {
    path_pattern           = "fonts/*"
    target_origin_id       = "S3-${aws_s3_bucket.web.id}"
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    compress               = true
    cache_policy_id        = aws_cloudfront_cache_policy.media_immutable.id
  }

  # SPA fallback — return index.html for 404s (trailingSlash: true handles routing)
  custom_error_response {
    error_code            = 403
    response_code         = 200
    response_page_path    = "/index.html"
    error_caching_min_ttl = 0
  }

  custom_error_response {
    error_code            = 404
    response_code         = 404
    response_page_path    = "/404.html"
    error_caching_min_ttl = 10
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = var.web_acm_certificate_arn == ""
    acm_certificate_arn            = var.web_acm_certificate_arn != "" ? var.web_acm_certificate_arn : null
    ssl_support_method             = var.web_acm_certificate_arn != "" ? "sni-only" : null
    minimum_protocol_version       = var.web_acm_certificate_arn != "" ? "TLSv1.2_2021" : "TLSv1"
  }

  # CloudFront access logging omitted — requires S3 ACL which conflicts with
  # modern bucket ownership controls. Enable manually via AWS Console if needed.
}

# CloudFront function — handle trailing-slash URLs for Next.js static export
resource "aws_cloudfront_function" "url_rewrite" {
  name    = "${var.project}-url-rewrite"
  runtime = "cloudfront-js-2.0"
  comment = "Append /index.html to directory paths for Next.js static export"
  publish = true

  code = <<-JS
    function handler(event) {
      var request = event.request;
      var uri = request.uri;
      // If URI ends with / or has no extension, serve index.html
      if (uri.endsWith('/')) {
        request.uri += 'index.html';
      } else if (!uri.includes('.')) {
        request.uri += '/index.html';
      }
      return request;
    }
  JS
}

# ── Media distribution (media.novakidlife.com) ────────────────────────────────

resource "aws_cloudfront_distribution" "media" {
  enabled         = true
  is_ipv6_enabled = true
  http_version    = "http2and3"
  comment         = "NovaKidLife media CDN — ${var.environment}"

  aliases = var.web_acm_certificate_arn != "" ? [var.media_domain_name] : []

  origin {
    domain_name              = aws_s3_bucket.media.bucket_regional_domain_name
    origin_id                = "S3-${aws_s3_bucket.media.id}"
    origin_access_control_id = aws_cloudfront_origin_access_control.media.id
  }

  default_cache_behavior {
    target_origin_id       = "S3-${aws_s3_bucket.media.id}"
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD", "OPTIONS"]
    cached_methods         = ["GET", "HEAD"]
    compress               = true
    cache_policy_id        = aws_cloudfront_cache_policy.media_immutable.id
  }

  custom_error_response {
    error_code            = 403
    response_code         = 404
    response_page_path    = "/404.html"
    error_caching_min_ttl = 10
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = var.web_acm_certificate_arn == ""
    acm_certificate_arn            = var.web_acm_certificate_arn != "" ? var.web_acm_certificate_arn : null
    ssl_support_method             = var.web_acm_certificate_arn != "" ? "sni-only" : null
    minimum_protocol_version       = var.web_acm_certificate_arn != "" ? "TLSv1.2_2021" : "TLSv1"
  }
}
