-- Migration: create blog_posts table
-- Blog posts generated by content-generator Lambda (weekly roundups, date-specific, location-specific)

CREATE TABLE IF NOT EXISTS public.blog_posts (
    id               UUID        PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
    slug             TEXT        UNIQUE NOT NULL,
    title            TEXT        NOT NULL,
    meta_description TEXT,
    content          TEXT        NOT NULL,  -- full markdown content
    post_type        TEXT        NOT NULL
                                 CHECK (post_type IN (
                                     'weekend_roundup',
                                     'week_ahead',
                                     'location_specific',
                                     'free_events',
                                     'indoor',
                                     'date_specific'
                                 )),
    area             TEXT        CHECK (area IN (
                                     'nova',
                                     'fairfax',
                                     'loudoun',
                                     'arlington',
                                     'alexandria',
                                     'prince_william',
                                     'dc_adjacent'
                                 )),
    date_range_start DATE        NOT NULL,
    date_range_end   DATE        NOT NULL,
    event_ids        UUID[]      DEFAULT '{}',
    event_count      INTEGER     DEFAULT 0,
    hero_image_url   TEXT,
    published_at     TIMESTAMPTZ DEFAULT NOW(),
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- Prevent regenerating the same post type + area + start date
CREATE UNIQUE INDEX IF NOT EXISTS blog_posts_type_area_date_idx
    ON public.blog_posts (post_type, COALESCE(area, 'nova'), date_range_start);

-- Fast listing queries (newest first)
CREATE INDEX IF NOT EXISTS blog_posts_published_at_idx
    ON public.blog_posts (published_at DESC);

-- Filter by post type
CREATE INDEX IF NOT EXISTS blog_posts_post_type_idx
    ON public.blog_posts (post_type);

-- GIN index for event_ids array lookups
CREATE INDEX IF NOT EXISTS blog_posts_event_ids_idx
    ON public.blog_posts USING GIN (event_ids);

-- ── RLS ────────────────────────────────────────────────────────────────────────

ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

-- Anyone can read published posts
CREATE POLICY "blog_posts_public_read"
    ON public.blog_posts FOR SELECT
    USING (true);

-- Only service role can insert / update / delete
CREATE POLICY "blog_posts_service_write"
    ON public.blog_posts FOR ALL
    USING (auth.role() = 'service_role');

-- ── updated_at trigger ─────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.set_blog_posts_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER blog_posts_updated_at
    BEFORE UPDATE ON public.blog_posts
    FOR EACH ROW EXECUTE PROCEDURE public.set_blog_posts_updated_at();
